kafka.bootstrap-servers = localhost:9092
server.port = 1080

#-----------------------------------------------------------------------------------------------------------------------------------------
spring.pass.key = ${ENCRYPT_KEY_TEST:secret}
spring.segment = ${SEGMENT_TEST:dev}
#-----------------------------------------------------------------------------------------------------------------------------------------
spring.datasource.passwordLocalhost = postgres
spring.datasource.driverClassName = org.postgresql.Driver
#-----------------------------------------------------------------------------------------------------------------------------------------
spring.sslKafka.dev.bootstrapServers = dvccmc-00kfp001.innodev.local:9092 
spring.sslKafka.dev.trustStoreLocation = KafkaStore/dev/kafka-truststore.p12
spring.sslKafka.dev.trustStorePassword = ${ENCRYPT_KEY_TEST:secret}
spring.sslKafka.dev.keyStoreLocation = KafkaStore/dev/kafka-keystore.p12
spring.sslKafka.dev.keyStorePassword = ${ENCRYPT_KEY_TEST:secret}
spring.sslKafka.dev.keyPassword = ${ENCRYPT_KEY_TEST:secret}
spring.sslKafka.dev.trustStoreType = PKCS12
spring.sslKafka.dev.keyStoreType = PKCS12
spring.sslKafka.dev.autoCommit = true

spring.sslKafka.st.bootstrapServers = stccmc-00kfp001.innodev.local:9092 
spring.sslKafka.st.trustStoreLocation = KafkaStore/st/kafka-truststore.p12
spring.sslKafka.st.trustStorePassword = ${ENCRYPT_KEY_TEST:secret}
spring.sslKafka.st.keyStoreLocation = KafkaStore/st/kafka-keystore.p12
spring.sslKafka.st.keyStorePassword = ${ENCRYPT_KEY_TEST:secret}
spring.sslKafka.st.keyPassword = ${ENCRYPT_KEY_TEST:secret}
spring.sslKafka.st.trustStoreType = PKCS12
spring.sslKafka.st.keyStoreType = PKCS12
spring.sslKafka.st.autoCommit = true

#-----------------------------------------------------------------------------------------------------------------------------------------
spring.consumer.groupId = composition
spring.consumer.autoOffsetReset = earliest
#-----------------------------------------------------------------------------------------------------------------------------------------